In [1]:
import numpy as np

# 1. Numbers from 10 to 100 with step 10
arr = np.arange(10, 101, 10)
print("1.", arr)

1. [ 10  20  30  40  50  60  70  80  90 100]


In [2]:
# 2. 3 x 4 array of zeros
arr = np.zeros((3, 4))
print("\n2.\n", arr)


2.
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# 3. ndim, shape, size, dtype
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\n3.")
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)


3.
ndim: 2
shape: (2, 3)
size: 6
dtype: int64


In [4]:
# 4. Extract last element from 1D array
arr = np.array([10, 20, 30, 40, 50])
print("\n4. Last element:", arr[-1])


4. Last element: 50


In [5]:
# 5. Select first two columns of 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n5.\n", arr[:, :2])


5.
 [[1 2]
 [4 5]
 [7 8]]


In [6]:
# 6. Reshape 12 numbers into 3 x 4
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print("\n6.\n", matrix)


6.
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# 7. Transpose a 2 x 3 matrix
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\n7.\n", arr.T)


7.
 [[1 4]
 [2 5]
 [3 6]]


In [8]:
# 8. Multiply every element by 5
arr = np.array([1, 2, 3, 4, 5])
print("\n8.", arr * 5)


8. [ 5 10 15 20 25]


In [9]:
# 9. Feature matrix X with 5 samples and 3 features
X = np.array([
    [20, 30, 40],
    [60, 70, 80],
    [40, 50, 60],
    [80, 90, 100],
    [30, 40, 50]
])
print("\n9. Shape:", X.shape)


9. Shape: (5, 3)


In [10]:
# 10. Mean of each feature using axis=0
print("\n10. Feature means:", X.mean(axis=0))


10. Feature means: [46. 56. 66.]


In [11]:
# 11. Rows where first feature > 50
print("\n11.\n", X[X[:, 0] > 50])


11.
 [[ 60  70  80]
 [ 80  90 100]]


In [12]:
# 12. Standardize every feature column
mean = X.mean(axis=0)
std = X.std(axis=0)
X_standardized = (X - mean) / std
print("\n12.\n", X_standardized)


12.
 [[-1.2070197  -1.2070197  -1.2070197 ]
 [ 0.64993368  0.64993368  0.64993368]
 [-0.27854301 -0.27854301 -0.27854301]
 [ 1.57841037  1.57841037  1.57841037]
 [-0.74278135 -0.74278135 -0.74278135]]


In [13]:
# 13. Random matrix (10, 4) using fixed seed
np.random.seed(42)
random_matrix = np.random.rand(10, 4)
print("\n13.\n", random_matrix)


13.
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249]]


In [14]:
# 14. X @ weights
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

weights = np.array([0.1, 0.2, 0.3])

result = X @ weights
print("\n14.", result)


14. [1.4 3.2 5. ]


In [15]:
# 15. Add bias using broadcasting
bias = 5
result = X @ weights + bias
print("\n15.", result)


15. [ 6.4  8.2 10. ]


In [16]:
# 16. Calculate MSE
y_true = np.array([10, 20, 30])
y_pred = np.array([12, 18, 29])

mse = np.mean((y_true - y_pred) ** 2)
print("\n16. MSE:", mse)


16. MSE: 3.0


In [17]:
# 17. 28 x 28 grayscale image
image = np.zeros((28, 28))
print("\n17. Image shape:", image.shape)


17. Image shape: (28, 28)


In [18]:
# 18. Batch of 64 RGB images, 224 x 224
images = np.zeros((64, 224, 224, 3))
print("\n18. Image batch shape:", images.shape)


18. Image batch shape: (64, 224, 224, 3)


In [19]:
# 19. NaN-safe mean
arr = np.array([10, 20, np.nan, 30, 40])
print("\n19. NaN-safe mean:", np.nanmean(arr))


19. NaN-safe mean: 25.0


In [20]:
# 20. Difference between A * B and A @ B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("\n20. A * B:\n", A * B)
print("A @ B:\n", A @ B)


20. A * B:
 [[ 5 12]
 [21 32]]
A @ B:
 [[19 22]
 [43 50]]
